### PR TITLE
Fix deprecated calls to hash API

### LINKED ISSUE #37: Hash functions use deprecated API calls
mbedtls_sha256_starts() and mbedtls_sha256_finish() are deprecated; we should use mbedtls_sha256_starts_ret() and mbedtls_sha256_finish_ret() and check the return code. Example in ssl_tls.c:

    if( ( ret = mbedtls_md_setup( &ctx, md_info, 0 ) ) != 0 )
    {
        MBEDTLS_SSL_DEBUG_RET( 1, "mbedtls_md_setup", ret );
        goto exit;
    }
    if( ( ret = mbedtls_md_starts( &ctx ) ) != 0 )
    {
        MBEDTLS_SSL_DEBUG_RET( 1, "mbedtls_md_starts", ret );
        goto exit;
    }
    if( ( ret = mbedtls_md_update( &ctx, ssl->handshake->randbytes, 64 ) ) != 0 )
    {
        MBEDTLS_SSL_DEBUG_RET( 1, "mbedtls_md_update", ret );
        goto exit;
    }
    if( ( ret = mbedtls_md_update( &ctx, data, data_len ) ) != 0 )
    {
        MBEDTLS_SSL_DEBUG_RET( 1, "mbedtls_md_update", ret );
        goto exit;
    }
    if( ( ret = mbedtls_md_finish( &ctx, hash ) ) != 0 )
    {
        MBEDTLS_SSL_DEBUG_RET( 1, "mbedtls_md_finish", ret );
        goto exit;
    }

### PR DESCRIPTION
**Pull request by gbryant-arm**
Fixes #37.

Future work:
* We might consider using a more generic API (`mbedtls_md_starts()`, `mbedtls_md_finish()`, etc.) instead of an API specific to hash functions (`mbedtls_md_starts()`, `mbedtls_sha256_finish_ret()`). Going further, we could unify `ssl_calc_*_tls_sha*()` and `ssl_update_checksum_sha*()`

### CODE REVIEW

File: library/ssl_tls13_client.c [hunk 1]
```diff
@@ -907,16 +959,17 @@ int mbedtls_ssl_create_binder( mbedtls_ssl_context *ssl, unsigned char *psk, siz
     else
 #endif
 #if defined(MBEDTLS_SHA512_C)
-        if( suite_info->mac == MBEDTLS_MD_SHA384 )
-        {
-            mbedtls_sha512_free( &sha512 );
-        }
-        else
+    if( suite_info->mac == MBEDTLS_MD_SHA384 ||
+        suite_info->mac == MBEDTLS_MD_SHA512 )
```
Comment (hanno-becker) [inline library/ssl_tls13_client.c:963]: Why was this change made? It doesn't seem to fall into the pattern of replacing deprecated functions by their new variants?

**Review by hanno-becker — CHANGES_REQUESTED** [review]
The PR doesn't build for me - could you investigate?

File: library/ssl_tls13_client.c (hunk 1 above)
Comment (gbryant-arm) [reply library/ssl_tls13_client.c:963]: Since we're using the same context in the case of both MBEDTLS_MD_SHA384 and MBEDTLS_MD_SHA512, we should free it in any of those cases.
You're right, it's orthogonal to the PR's objective. I guess I fixed without noticing

**Review by hanno-becker — CHANGES_REQUESTED** [review]
Thanks for the update, @gbryant-arm, it compiles and passes most tests now. However, there are still two tests in `ssl-opt.sh` failing. Can you investigate?

**Review by hanno-becker — APPROVED** [review]
